
INSERT INTO "BOOK_RIDE"("ACCEPT_THE_RIDE","BOOK_RIDE_ID","DISTANCE_IN_KM","fare_in$","DESTINATION_LOCATION","DURATION","PICK_UP_LOCATION","REQUEST_DRIVERU")VALUES(false,1,0,0,'','','', '');
INSERT INTO "WALLET"("MONEY","WALLET_ID")VALUES(100, 1);
INSERT INTO "PASSENGER"("BOOK_RIDE_ID","IS_TEEN_ACCOUNT","ON_RIDE","PASSENGER_ID","WALLET_ID","PHONE_NUMBER","EMAIL","GENDER","NAME","PASSWORD","ROLE")VALUES(1,false,false,1,1,1234567890,'hetul@gmail.com','male','hetul','$2a$10$s/8B1BmXsfXNG7CQbZMtzuwBcCI8G.VfuSgIpPPFOvvFyKGoH7RKO','ROLE_USER');


INSERT INTO "BOOK_RIDE"("ACCEPT_THE_RIDE","BOOK_RIDE_ID","DISTANCE_IN_KM","fare_in$","DESTINATION_LOCATION","DURATION","PICK_UP_LOCATION","REQUEST_DRIVERU")VALUES(false,2,0,0,'','','', '');
INSERT INTO "WALLET"("MONEY","WALLET_ID")VALUES(200, 2);
INSERT INTO "PASSENGER"("BOOK_RIDE_ID","IS_TEEN_ACCOUNT","ON_RIDE","PASSENGER_ID","WALLET_ID","PHONE_NUMBER","EMAIL","GENDER","NAME","PASSWORD","ROLE")VALUES(2,false,false,2,2,7891234567,'seemant@gmail.com','male','seemant','$2a$10$UNnxCIE/60mfBQmdJyPJOOQRwCm85bVewkOHmXStBg.4uSmTly6iu','ROLE_USER');



INSERT INTO "BOOK_RIDE"("ACCEPT_THE_RIDE","BOOK_RIDE_ID","DISTANCE_IN_KM","fare_in$","DESTINATION_LOCATION","DURATION","PICK_UP_LOCATION","REQUEST_DRIVERU")VALUES(false,3,0,0,'','','', '');
INSERT INTO "WALLET"("MONEY","WALLET_ID")VALUES(300, 3);
INSERT INTO "PASSENGER"("BOOK_RIDE_ID","IS_TEEN_ACCOUNT","ON_RIDE","PASSENGER_ID","WALLET_ID","PHONE_NUMBER","EMAIL","GENDER","NAME","PASSWORD","ROLE")VALUES(3,false,false,3,3,7894561230,'rohan@gmail.com','male','rohan','$2a$10$tgkWybC3oeaNK7YMNPEk6uXyFzQLR0QaJLU7YWKleqWfiO5ioH4Aq','ROLE_USER');



INSERT INTO "BOOK_RIDE"("ACCEPT_THE_RIDE","BOOK_RIDE_ID","DISTANCE_IN_KM","fare_in$","DESTINATION_LOCATION","DURATION","PICK_UP_LOCATION","REQUEST_DRIVERU")VALUES(false,4,0,0,'','','', '');
INSERT INTO "WALLET"("MONEY","WALLET_ID")VALUES(100, 4);
INSERT INTO "PASSENGER"("BOOK_RIDE_ID","IS_TEEN_ACCOUNT","ON_RIDE","PASSENGER_ID","WALLET_ID","PHONE_NUMBER","EMAIL","GENDER","NAME","PASSWORD","ROLE")VALUES(4,false,false,4,4,4561237890,'manik@gmail.com','male','manik','$2a$10$C6/BypTrM4JjVzkcsXmb9uSHL4gxRa6OrlAcbbYA2ZzKTZpW32g0i','ROLE_USER');
